### ISSUE TITLE
Problems with path identification when run directly from the repo

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/phylogenetic-compression-supplement#3]
```
$ ../mof.py clusters
[2020-10-23 17:47:49.786642] MoF starting
Traceback (most recent call last):
  File "../mof.py", line 369, in <module>
    main()
  File "../mof.py", line 355, in main
    print_clusters(urls=args.u, accessions=args.a, header=args.h)
  File "../mof.py", line 109, in print_clusters
    du = get_clusters_urls()
  File "../mof.py", line 63, in get_clusters_urls
    with open(URLS_FN) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/downloads.tsv'
```

**Comment by karel-brinda** [comment]
Fixed by https://github.com/karel-brinda/mof/commit/dc0fa31414261dcbfbe2d90c757786be512404c3
